<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0cb2d9cf91.js"></script>
    <style type="text/css">
        body {
            background: url(img/academia-fondo.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
    <title>ACADEMIA DE GOLF</title>
</head>

<body>
    <?php include "header.php"; ?>

    <div class="galeria" style="position:relative; top:10rem;">
        <h1>ACADEMIA DE GOLF ! ! ! ! !</h1>
        <div class="linea"></div>
        <div class="contenedor-imagenes">
            <div class="imagen">
                <img src="img/acad1.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad2.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad3.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad4.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad5.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad6.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad7.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
            <div class="imagen">
                <img src="img/acad8.jpg" alt="" ;>
                <div class="inscripcion">
                    <h2>Inscribite....</H2>
                </div>
            </div>
        </div>
    </div>
    <?php include "footer.html" ?>

    <!-- Optional JavaScript-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>