<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0cb2d9cf91.js"></script>
    <style type="text/css">
        body {
            background: url(img/accesorios-fondo.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        
    </style>
    <title>ACCESORIOS</title>
</head>

<body>
    <?php include "header.php"; ?>

        <div class="container" style="position: relative; left: 0px; top: 105px;">
        <div class="row">
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style="width:18rem">
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        BOLSA
                    </div>
                    <img src="img/bolsacall_resultado.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">Callaway</h3>
                        <p class="card-text">Impermeable!</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        BOLSA CALLAWAY
                    </div>
                    <img src="img/bolsacarro_resultado.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">CALLAWAY</h3>
                        <p class="card-text">Para Usar Con Carro</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style=" width:100%">
                        GUANTES
                    </div>
                    <img src="img/guantefj_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">FOOT JOY</h3>
                        <p class="card-text">Cabretilla</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>

            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style=" width:100%">
                        GUANTES
                    </div>
                    <img src="img/guantes_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">CALLAWAY</h3>
                        <p class="card-text">Varios Colores</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        GORRAS
                    </div>
                    <img src="img/gorrastit_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">TITLELEIST</h3>
                        <p class="card-text">Varios Colores</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        GORRAS
                    </div>
                    <img src="img/gorrasm3_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">TAYLOR MADE</h3>
                        <p class="card-text">Modelo M3</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PELOTAS
                    </div>
                    <img src="img/pelotasprov1_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">TITLEIST PROV 1</h3>
                        <p class="card-text">#1 en el PGA Tour</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PELOTAS
                    </div>
                    <img src="img/pelotastour_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">TITLEIST</h3>
                        <p class="card-text">Tour Soft</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>

            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PELOTAS
                    </div>
                    <img src="img/pelotascall_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">CALLAWAY</h3>
                        <p class="card-text">Chrome Soft</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>

            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        ZAPATO ADIDAS
                    </div>
                    <img src="img/zapatoadidas_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">ADIDAS</h3>
                        <p class="card-text">ZAPATO ADIDAS 2019</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>

            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        ZAPATO FJ
                    </div>
                    <img src="img/zapatoSFJ_resultado.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">FJ</h3>
                        <p class="card-text">ZAPATO FJ 2019</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    
    <?php include "footer.html" ?>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>