<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0cb2d9cf91.js"></script>
    <style type="text/css">
        body {
            background: url(img/puters-fondo1.jpg) no-repeat center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        
    </style>
    <title>PUTTERS</title>
</head>

<body>
    <?php include "header.php"; ?>

    <div class="container" style="position: relative; left: 0px; top: 105px;">
        <div class="row">
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style="width:18rem">
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PUTTER ODDYSSEY
                    </div>
                    <img src="img/putteroddy.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body" style="height:14.5rem">
                        <h3 class="card-title">Consulte por modelos y varas</h3>
                        <p class="card-text"></p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PUTTER ODDYSEY
                    </div>
                    <img src="img/putterody.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">Consulte por modelos y varas</h3>
                        <p class="card-text"></p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style=" width:100%">
                        PUTTER PING
                    </div>
                    <img src="img/putterping.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">PING</h3>

                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PUTTER PING
                    </div>
                    <img src="img/putterpings.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">Tenemos la vara para usted</h3>

                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            <div class="col-md-auto col-lg-4">
                <div class="card mt-5" style=width:18rem>
                    <div class=" card-header text-white bg-dark" style="width:100%">
                        PUTTER TAYLOR MADE M6
                    </div>
                    <img src="img/puttertay.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="height:10rem">
                        <h3 class="card-title">TAYLOR MADE M6</h3>
                        <p class="card-text">Ultimo modelo!</p>
                        <a href="#" class="card-link">Ver Detalles</a>
                        <a href="#" class="btn btn-success">Agregar al Carrito</a>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <?php include "footer.html" ?>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>